#:schema node_modules/wrangler/config-schema.json
name = "workers-graphql-server"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

rules = [
  { type = "Text", globs = ["**/*.graphql"], fallthrough = true }
]

[observability]
enabled = true
